### ISSUE TITLE
Version 0.7.0 binary does not run on Ubuntu 16.04

### ISSUE THREAD

**Issue by dietmarw** [THM-MoTE/MoVE#2]
Just tried to follow your installation instructions but get:

```
~/Downloads$ java -jar Move-0.7.0.jar 
Error: Could not find or load main class de.thm.move.MoveApp
```

I checked also the Java version:
```
~/Downloads$ java -version
openjdk version "1.8.0_121"
OpenJDK Runtime Environment (build 1.8.0_121-8u121-b13-0ubuntu1.16.04.2-b13)
OpenJDK 64-Bit Server VM (build 25.121-b13, mixed mode)
```
What am I missing?

**Comment by hobbypunk90** [comment]
Do you have the JavaFX package for Ubuntu openjfx installed?

**Comment by dietmarw** [comment]
Of course not ;-), Thanks that solved it. Maybe updating in the dependencies for the "installation" in the README would be good.
